import json
import uuid
from typing import Any

from companyos.providers.llm import (
    MOCK_PROVIDER,
    LLMMessage,
    LLMResponse,
    ToolCall,
    ToolSpec,
    approximate_tokens,
    local_embeddings,
)

MOCK_MODEL = "mock-1"
MOCK_NOTICE = "> Generated by the offline mock model — configure an AI provider in Settings for real output."

# Planned steps: key, role, title, depends_on, output type
MOCK_PLAN_STEPS: list[tuple[str, str, str, list[str], str]] = [
    ("market_research", "market_researcher", "Market and competitor research", [], "research_report"),
    (
        "product_definition",
        "product_manager",
        "Define the MVP and product requirements",
        ["market_research"],
        "prd",
    ),
    (
        "architecture",
        "technical_architect",
        "Design the technical architecture",
        ["product_definition"],
        "architecture",
    ),
    (
        "positioning",
        "marketing_strategist",
        "Positioning and messaging strategy",
        ["product_definition"],
        "strategy",
    ),
    ("implementation_plan", "software_engineer", "Prepare the implementation plan", ["architecture"], "plan"),
    ("launch_copy", "copywriter", "Write launch copy and social posts", ["positioning"], "copy"),
]

ROLE_SECTIONS: dict[str, list[str]] = {
    "market_researcher": [
        "Executive summary",
        "Market landscape",
        "Target segments",
        "Competitive landscape",
        "Opportunities and risks",
        "Confidence and sources",
    ],
    "product_manager": [
        "Problem statement",
        "Target users",
        "MVP scope",
        "User stories",
        "Success metrics",
        "Open questions",
    ],
    "technical_architect": [
        "Architecture overview",
        "Core components",
        "Data model",
        "Integrations",
        "Security considerations",
        "Delivery phases",
    ],
    "software_engineer": [
        "Milestones",
        "Repository structure",
        "Work breakdown",
        "Testing strategy",
        "Risks",
    ],
    "marketing_strategist": [
        "Ideal customer profile",
        "Value proposition",
        "Messaging pillars",
        "Channels",
        "Launch timeline",
    ],
    "copywriter": ["Headline options", "Landing page hero", "Social posts", "Launch email"],
}


def _subject(hints: dict[str, Any]) -> str:
    return str(hints.get("objective_title") or hints.get("task_title") or "the objective")


def _section_body(role_key: str, section: str, hints: dict[str, Any], revision: int) -> str:
    subject = _subject(hints)
    if role_key == "copywriter" and section == "Social posts":
        tone = "technical, concise" if revision else "friendly"
        return (
            f"**LinkedIn ({tone}):** Introducing {subject}. Built for teams who want results, not demos. "
            "See how it works →\n\n"
            f"**X:** {subject} is here. Faster workflows, measurable outcomes. Early access is open."
        )
    if role_key == "copywriter" and section == "Headline options":
        if revision:
            return f"1. {subject}: ship measurable results in weeks\n2. The technical buyer's shortcut to {subject}"
        return f"1. Meet {subject}\n2. The smarter way forward"
    return (
        f"- Focus for **{subject}**: {section.lower()} aligned with the objective.\n"
        f"- Derived from: {str(hints.get('task_instructions') or '')[:160]}\n"
        "- Assumptions are explicit; validate with a configured AI provider and live data."
    )


def mock_document(hints: dict[str, Any]) -> str:
    role_key = str(hints.get("role_key", ""))
    revision = int(hints.get("revision", 0))
    sections = ROLE_SECTIONS.get(role_key, ["Summary", "Approach", "Deliverable", "Next steps"])
    lines = [f"# {hints.get('task_title', 'Deliverable')}", "", MOCK_NOTICE, ""]
    if revision:
        lines += [
            f"_Revision {revision}: addressed reviewer feedback — {hints.get('review_feedback', '')}_",
            "",
        ]
    for section in sections:
        lines += [f"## {section}", "", _section_body(role_key, section, hints, revision), ""]
    return "\n".join(lines)


def mock_plan(hints: dict[str, Any]) -> dict[str, Any]:
    available = {role["role_key"] for role in hints.get("roles", [])}
    steps = [step for step in MOCK_PLAN_STEPS if step[1] in available]
    keys = {step[0] for step in steps}
    tasks = [
        {
            "key": key,
            "title": title,
            "role": role,
            "instructions": f"{title} for: {hints.get('objective_title', '')}. {hints.get('instruction', '')[:400]}",
            "depends_on": [dependency for dependency in depends_on if dependency in keys],
            "expected_output_type": output_type,
            "acceptance_criteria": ["Addresses the objective directly", "Clear structure and next steps"],
            "requires_review": True,
            "priority": "normal",
        }
        for key, role, title, depends_on, output_type in steps
    ]
    return {
        "summary": f"Plan for '{hints.get('objective_title', '')}': research first, then product definition, "
        "then engineering and marketing in parallel.",
        "tasks": tasks,
    }


def mock_review(hints: dict[str, Any]) -> dict[str, Any]:
    # Request one revision on first-pass copy to exercise the review loop deterministically
    if hints.get("role_key") == "copywriter" and int(hints.get("revision_count", 0)) == 0:
        return {
            "verdict": "revise",
            "score": 6,
            "feedback": "CTA is too generic. Revise toward technical buyers and tighten the headline options.",
            "issues": ["Generic call to action", "Headlines lack a concrete outcome"],
        }
    return {"verdict": "accept", "score": 8, "feedback": "Meets the acceptance criteria.", "issues": []}


def mock_report(hints: dict[str, Any]) -> dict[str, Any]:
    stats = hints.get("stats", {})
    failed = int(stats.get("tasks_failed", 0))
    pending = int(stats.get("approvals_pending", 0))
    recommendation = "Proceed with the MVP." if failed == 0 else "Resolve the failed work before proceeding."
    return {
        "headline": f"{stats.get('objective_title', 'Objective')} — {stats.get('status', '')}",
        "overall_assessment": (
            f"{stats.get('tasks_completed', 0)} of {stats.get('tasks_total', 0)} tasks completed by "
            f"{stats.get('agents_involved', 0)} agents. {failed} failed. {pending} approvals pending."
        ),
        "key_findings": [f"Delivered: {title}" for title in stats.get("completed_titles", [])][:8],
        "recommendation": recommendation,
        "next_actions": (["Review pending approvals in the CEO Inbox"] if pending else [])
        + ["Configure an AI provider for production-quality output"],
        "risks": [f"Failed: {title}" for title in stats.get("failed_titles", [])],
    }


class MockLLMProvider:
    name = MOCK_PROVIDER
    is_mock = True

    async def complete(
        self,
        *,
        model: str,
        messages: list[LLMMessage],
        tools: list[ToolSpec] | None = None,
        temperature: float = 0.3,
        json_mode: bool = False,
        purpose: str = "general",
        hints: dict[str, Any] | None = None,
    ) -> LLMResponse:
        hints = hints or {}
        content: str | None = None
        tool_calls: list[ToolCall] = []
        if purpose == "plan":
            content = json.dumps(mock_plan(hints))
        elif purpose == "review":
            content = json.dumps(mock_review(hints))
        elif purpose == "report":
            content = json.dumps(mock_report(hints))
        elif purpose == "execute":
            tool_calls, content = self._next_execution_step(messages, tools or [], hints)
        else:
            content = "Acknowledged."
        prompt_text = " ".join(message.content or "" for message in messages)
        return LLMResponse(
            content=content,
            tool_calls=tool_calls,
            input_tokens=approximate_tokens(prompt_text),
            output_tokens=approximate_tokens(content or json.dumps([c.arguments for c in tool_calls])),
            model=MOCK_MODEL,
            provider=self.name,
        )

    def _next_execution_step(
        self, messages: list[LLMMessage], tools: list[ToolSpec], hints: dict[str, Any]
    ) -> tuple[list[ToolCall], str | None]:
        available = {tool.name for tool in tools}
        used = {call.name for message in messages for call in message.tool_calls}

        def call(name: str, arguments: dict[str, Any]) -> tuple[list[ToolCall], None]:
            return [ToolCall(id=f"call_{uuid.uuid4().hex[:12]}", name=name, arguments=arguments)], None

        if "search_company_knowledge" in available and "search_company_knowledge" not in used:
            return call("search_company_knowledge", {"query": str(hints.get("task_title", ""))})
        if "create_artifact" in available and "create_artifact" not in used:
            title = str(hints.get("task_title", "Deliverable"))
            return call(
                "create_artifact",
                {
                    "title": title,
                    "filename": title.lower().replace(" ", "-")[:60] + ".md",
                    "content": mock_document(hints),
                    "kind": str(hints.get("expected_output_type", "document")),
                },
            )
        social_ready = hints.get("role_key") == "copywriter" and int(hints.get("revision", 0)) == 0
        if social_ready and "publish_social_post" in available and "publish_social_post" not in used:
            return call(
                "publish_social_post",
                {
                    "platform": "linkedin",
                    "content": f"Introducing {_subject(hints)}. Built for teams who want results. Early access open.",
                },
            )
        return [], f"Completed '{hints.get('task_title', 'task')}'. The deliverable was saved as an artifact."

    async def embed(self, texts: list[str], model: str) -> tuple[list[list[float]], int]:
        return local_embeddings(texts), 0
