"""objective criteria and evidence

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-05 21:57:35.480044
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from companyos.migration_utils import drop_tenant_rls, enable_tenant_rls

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence",
        sa.Column("objective_id", sa.Uuid(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("artifact_id", sa.Uuid(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("ref", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("source_title", sa.String(length=300), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("confidence", sa.String(length=8), nullable=False),
        sa.Column(
            "collected_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_evidence_agent_id_agents"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_evidence_artifact_id_artifacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["objective_id"],
            ["objectives.id"],
            name=op.f("fk_evidence_objective_id_objectives"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_evidence_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_evidence_task_id_tasks"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sa.UniqueConstraint("ref", name=op.f("uq_evidence_ref")),
    )
    op.create_index(op.f("ix_evidence_objective_id"), "evidence", ["objective_id"], unique=False)
    op.create_index(op.f("ix_evidence_organization_id"), "evidence", ["organization_id"], unique=False)
    op.add_column(
        "objectives",
        sa.Column(
            "acceptance_criteria",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    # ### end Alembic commands ###
    enable_tenant_rls("evidence")


def downgrade() -> None:
    drop_tenant_rls("evidence")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("objectives", "acceptance_criteria")
    op.drop_index(op.f("ix_evidence_organization_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_objective_id"), table_name="evidence")
    op.drop_table("evidence")
    # ### end Alembic commands ###
