"""budget ledger and model fallback

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-05 21:17:48.441504
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from companyos.migration_utils import drop_tenant_rls, enable_tenant_rls

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budget_ledgers",
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("scope_key", sa.String(length=64), nullable=False),
        sa.Column("limit_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("reserved_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("spent_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("scope IN ('objective', 'daily')", name=op.f("ck_budget_ledgers_valid_scope")),
        sa.CheckConstraint("reserved_usd >= 0", name=op.f("ck_budget_ledgers_reserved_non_negative")),
        sa.CheckConstraint("spent_usd >= 0", name=op.f("ck_budget_ledgers_spent_non_negative")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_budget_ledgers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_ledgers")),
        sa.UniqueConstraint("organization_id", "scope", "scope_key", name="uq_budget_ledger_scope"),
    )
    op.create_index(
        op.f("ix_budget_ledgers_organization_id"), "budget_ledgers", ["organization_id"], unique=False
    )
    op.create_table(
        "budget_reservations",
        sa.Column("objective_id", sa.Uuid(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("daily_key", sa.String(length=16), nullable=False),
        sa.Column("purpose", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("actual_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('reserved', 'settled', 'released', 'expired')",
            name=op.f("ck_budget_reservations_valid_status"),
        ),
        sa.CheckConstraint("amount_usd >= 0", name=op.f("ck_budget_reservations_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_budget_reservations_agent_id_agents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["objective_id"],
            ["objectives.id"],
            name=op.f("fk_budget_reservations_objective_id_objectives"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_budget_reservations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_budget_reservations_task_id_tasks"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_reservations")),
    )
    op.create_index(
        "ix_budget_reservations_open",
        "budget_reservations",
        ["organization_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_budget_reservations_organization_id"),
        "budget_reservations",
        ["organization_id"],
        unique=False,
    )
    op.add_column("model_usage", sa.Column("fallback_from_model", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###
    enable_tenant_rls("budget_ledgers")
    enable_tenant_rls("budget_reservations")


def downgrade() -> None:
    drop_tenant_rls("budget_ledgers")
    drop_tenant_rls("budget_reservations")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_usage", "fallback_from_model")
    op.drop_index(op.f("ix_budget_reservations_organization_id"), table_name="budget_reservations")
    op.drop_index("ix_budget_reservations_open", table_name="budget_reservations")
    op.drop_table("budget_reservations")
    op.drop_index(op.f("ix_budget_ledgers_organization_id"), table_name="budget_ledgers")
    op.drop_table("budget_ledgers")
    # ### end Alembic commands ###
