"""escalations

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 20:17:39.977383
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from companyos.migration_utils import drop_tenant_rls, enable_tenant_rls

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "escalations",
        sa.Column("objective_id", sa.Uuid(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("approval_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "review_exhausted",
                "decision_required",
                "insufficient_information",
                "conflicting_evidence",
                "ambiguous_scope",
                "action_outcome_unknown",
                name="escalationkind",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "RESOLVED", "CANCELLED", name="escalationstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("resolution_option", sa.String(length=64), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=False),
        sa.Column("resolved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_escalations_agent_id_agents"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
            name=op.f("fk_escalations_approval_id_approvals"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["objective_id"],
            ["objectives.id"],
            name=op.f("fk_escalations_objective_id_objectives"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_escalations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
            name=op.f("fk_escalations_resolved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_escalations_task_id_tasks"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_escalations")),
    )
    op.create_index(
        "ix_escalations_objective_status", "escalations", ["objective_id", "status"], unique=False
    )
    op.create_index(op.f("ix_escalations_organization_id"), "escalations", ["organization_id"], unique=False)
    op.create_index(op.f("ix_escalations_task_id"), "escalations", ["task_id"], unique=False)
    # ### end Alembic commands ###
    enable_tenant_rls("escalations")


def downgrade() -> None:
    drop_tenant_rls("escalations")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_escalations_task_id"), table_name="escalations")
    op.drop_index(op.f("ix_escalations_organization_id"), table_name="escalations")
    op.drop_index("ix_escalations_objective_status", table_name="escalations")
    op.drop_table("escalations")
    # ### end Alembic commands ###
