"""approval execution state

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-05 21:26:22.815573
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "approvals",
        sa.Column(
            "execution_status",
            sa.Enum(
                "NOT_STARTED",
                "EXECUTING",
                "EXECUTED",
                "FAILED",
                "UNKNOWN",
                name="executionstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
            server_default="NOT_STARTED",
        ),
    )
    op.add_column("approvals", sa.Column("idempotency_key", sa.String(length=80), nullable=True))
    op.add_column(
        "approvals", sa.Column("execution_attempts", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column("approvals", sa.Column("execution_started_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("approvals", sa.Column("execution_error", sa.Text(), nullable=True))
    # Backfill: every existing approval gets a key; already-executed ones are marked EXECUTED
    op.execute("UPDATE approvals SET idempotency_key = 'act_' || replace(id::text, '-', '')")
    op.execute(
        "UPDATE approvals SET execution_status = 'EXECUTED', execution_attempts = 1 WHERE executed_at IS NOT NULL"
    )
    op.alter_column("approvals", "idempotency_key", nullable=False)
    op.create_unique_constraint(op.f("uq_approvals_idempotency_key"), "approvals", ["idempotency_key"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_approvals_idempotency_key"), "approvals", type_="unique")
    op.drop_column("approvals", "execution_error")
    op.drop_column("approvals", "execution_started_at")
    op.drop_column("approvals", "execution_attempts")
    op.drop_column("approvals", "idempotency_key")
    op.drop_column("approvals", "execution_status")
    # ### end Alembic commands ###
