"""notification outbox

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-05 21:34:55.290180
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("html_body", sa.Text(), nullable=False, server_default=""))
    op.add_column("notifications", sa.Column("text_body", sa.Text(), nullable=False, server_default=""))
    op.add_column("notifications", sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"))
    op.add_column(
        "notifications",
        sa.Column(
            "next_attempt_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column("notifications", sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True))
    # Legacy rows were sent inline; give them unique keys so the column can be NOT NULL
    op.execute("UPDATE notifications SET dedupe_key = 'legacy:' || id::text WHERE dedupe_key IS NULL")
    op.alter_column("notifications", "dedupe_key", existing_type=sa.VARCHAR(length=200), nullable=False)
    op.create_index("ix_notifications_due", "notifications", ["status", "next_attempt_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notifications_due", table_name="notifications")
    op.alter_column("notifications", "dedupe_key", existing_type=sa.VARCHAR(length=200), nullable=True)
    op.drop_column("notifications", "locked_at")
    op.drop_column("notifications", "next_attempt_at")
    op.drop_column("notifications", "attempts")
    op.drop_column("notifications", "text_body")
    op.drop_column("notifications", "html_body")
    # ### end Alembic commands ###
